### ISSUE TITLE
Gripper slowly slumps down

### ISSUE THREAD

**Issue by BengisuA14** [intuitivecomputing/ur5_with_robotiq_gripper#1]
When I start the simulation with gazebo, the gripper slowly slumps down. I suspect this is due to the gravity factor since the gripper stays still when I remove gravity. What could be the issue? Is there a way to fix this problem? (without changing gravity)

I have the following Errors:

[ERROR] [1563347253.284276677, 0.153000000]: GazeboRosControlPlugin missing <legacyModeNS> while using DefaultRobotHWSim, defaults to true.
This setting assumes you have an old package with an old implementation of DefaultRobotHWSim, where the robotNamespace is disregarded and absolute paths are used instead.
If you do not want to fix this issue in an old package just set <legacyModeNS> to true.

[ INFO] [1563347253.284324342, 0.153000000]: Starting gazebo_ros_control plugin in namespace: /
[ INFO] [1563347253.286237655, 0.153000000]: gazebo_ros_control plugin is waiting for model URDF in parameter [robot_description] on the ROS param server.
[spawn_urdf-4] process has finished cleanly
log file: /home/bengisu/.ros/log/8a862dea-a861-11e9-93b7-484520428335/spawn_urdf-4*.log
[ERROR] [1563347253.404065725, 0.153000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/shoulder_pan_joint
[ERROR] [1563347253.405194378, 0.153000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/shoulder_lift_joint
[ERROR] [1563347253.406268884, 0.153000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/elbow_joint
[ERROR] [1563347253.407274436, 0.153000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/wrist_1_joint
[ERROR] [1563347253.408312816, 0.153000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/wrist_2_joint
[ERROR] [1563347253.409407426, 0.153000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/wrist_3_joint
[ WARN] [1563347253.409485648, 0.153000000]: Deprecated syntax, please prepend 'hardware_interface/' to 'PositionJointInterface' within the <hardwareInterface> tag in joint 'finger_joint'.
[ERROR] [1563347253.410588337, 0.153000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/finger_joint

**Comment by yepw** [comment]
Hi @BengisuA14 , could you please try to clone this repo [roboticsgroup_gazebo_plugins](https://github.com/roboticsgroup/roboticsgroup_gazebo_plugins) to your `catkin_ws/src` and build the project again? As far as I know, the error message you reported can be ignored. The gripper slumps down may because the mimic joint plugin doesn't work well.
https://github.com/intuitivecomputing/ur5_with_robotiq_gripper/blob/2200bf3b8b4bf23357f4f9a0056e7bdaac6f1f99/icl_ur5_setup_description/urdf/robotiq_arg2f_transmission.xacro#L15

**Comment by BengisuA14** [comment]
Thank you, there was a problem with dependencies. I solved it.
