### ISSUE TITLE
Applying PID control

### ISSUE THREAD

**Issue by Alchemist77** [intuitivecomputing/ur5_with_robotiq_gripper#2]
Hi Yuxiang Gao and Yeping Wang,

Thank you for sharing this repo. It is very useful for working in gazebo simulation
Actually, I am doing grasping an object, but without PID and mimic gazebo plugin gripper always slip or get crazy situation during grasping.
Have you any experienced grasping with your repo. I tried to grasp an object, but gripper cannot grasp it. Also, I applied mimic plugin and PID in your repo.. I still have the problem of grasping task.

------------------------------------------------------
example applying PID
gazebo_ros_control:
  pid_gains:
    # these gains are used by the gazebo_ros_control plugin
    shoulder_pan_joint:
      p: 0.0
      i: 0.0
      d: 0.0
      i_clamp: 0.0
      antiwindup: false
      publish_state: true
--------------------------------------------------------------------------
Also, I applied roboticsgroup_gazebo_plugins with mimic joint as well.

If you have any experience or suggestion, I really appreciate it. 

Thank you!

Best regards,
Jaeseok

**Comment by Alchemist77** [comment]
Also, I applied roboticsgroup_gazebo_plugins with mimic joint as well.

**Comment by yepw** [comment]
Sorry, @Alchemist77. I don't have much experience in this, but I think it would be super cool to simulate grasping in Gazebo. I remember I have seen one relevant question. Hope it is helpful.
http://answers.gazebosim.org/question/14887/object-slips-out-of-gripper-gazebo-7-ur5-robotiq-3-finger/
