### ISSUE TITLE
controlling gripper in rviz

### ISSUE THREAD

**Issue by BengisuA14** [intuitivecomputing/ur5_with_robotiq_gripper#3]
Hello,
thank you again for this repository. I can't control (open/close) the gripper using Motion planning/planning part. The action is planned but cannot be executed. Do you know how to solve this issue?

Here are the errors I get:

[ WARN] [1564146902.193136269, 33.811000000]: Interactive marker 'EE:goal_fts_toolside' contains unnormalized quaternions. This warning will only be output once but may be true for others; enable DEBUG messages for ros.rviz.quaternions to see more details.
[ INFO] [1564146967.055749230, 98.124000000]: No active joints or end effectors found for group 'gripper'. Make sure that kinematics.yaml is loaded in this node's namespace.
[ INFO] [1564146967.056074333, 98.124000000]: Constructing new MoveGroup connection for group 'gripper' in namespace ''
[ INFO] [1564146967.269758619, 98.337000000]: Ready to take commands for planning group gripper.
[ INFO] [1564146967.269797988, 98.337000000]: Looking around: no
[ INFO] [1564146967.269816936, 98.337000000]: Replanning: no
[ INFO] [1564146971.345647378, 102.395000000]: ABORTED: Solution found but controller failed during execution

*--------------------------------------------------------------------------------------------------------------------------------*

[ INFO] [1564146969.671732036, 100.728000000]: RRTConnect: Created 4 states (2 start + 2 goal)
[ INFO] [1564146969.672085549, 100.729000000]: ParallelPlan::solve(): Solution found by one or more threads in 0.001410 seconds
[ INFO] [1564146969.677407458, 100.734000000]: SimpleSetup: Path simplification took 0.005186 seconds and changed from 3 to 2 states
[ INFO] [1564146971.330634915, 102.380000000]: Execution request received
[ INFO] [1564146971.330720920, 102.380000000]: Returned 1 controllers in list
[ERROR] [1564146971.330782080, 102.380000000]: Unable to identify any set of controllers that can actuate the specified joints: [ finger_joint ]
[ERROR] [1564146971.330830374, 102.380000000]: Known controllers and their joints:
controller 'arm_controller' controls joints:
  elbow_joint
  shoulder_lift_joint
  shoulder_pan_joint
  wrist_1_joint
  wrist_2_joint
  wrist_3_joint

Thanks in advance

**Comment by yepw** [comment]
Hi, it seems that the gripper controller is not loaded. Could you try `rostoplic list`? There should be several topic names beginning with `gripper/follow_joint_trajectory/`

**Comment by BengisuA14** [comment]
Well, it does not seem to be there. I suspect it might be because I changed in gazebo configs the gripper controller to GripperActionController from JointTrajectoryController in order to easily control the gripper from the command line. 
Do you know if/how I can use robotiq_2f_gripper_control of robotiq for that purpose using this package on a simulation?

**Comment by yepw** [comment]
Hi, you may need to change this file.
```
icl_ur5_setup_moveit_config/config/controllers_sim.yaml
```
You can also take a look at `icl_ur5_setup_moveit_config/config/controllers.yaml`, which uses a GripperActionController.

**Comment by yepw** [comment]
Using GipperActionController makes more sense to us, so we have updated it. @BengisuA14 please check the latest master branch. https://github.com/intuitivecomputing/ur5_with_robotiq_gripper/commit/6e62fbc3279db525b8ade30ac4f8c638d906549b
