### ISSUE TITLE
How to make gripper close completely?

### ISSUE THREAD

**Issue by rcao-hk** [intuitivecomputing/ur5_with_robotiq_gripper#6]
Hi,

Thanks for your working on the robot model. I noticed the 140 gripper cannot close completely in gazebo simulation. How I can make it close completely? I check the urdf but don't know the solution yet. Could you give me some clues about it? By the way, could you info me the gazebo version you used here? Thank you.

Regards
Rui Cao

**Comment by jhaardt** [comment]
It has to do with the limits of the finger_joint, in the   **robotiq_arg2f_140_model_macro.xacro**
line 169:
` <limit lower="0" upper="0.775" velocity="2.0" effort="1000" /> `
increase the upper to close it further. 

My gazebo is Version 7.0.0. (ros kinetic)

**Comment by rcao-hk** [comment]
Hi,

I changed the upper limitation for it and the model is broken then. I think it is due to the improper limitation value of other links. I am trying to solve it. 

Regards.

**Comment by rcao-hk** [comment]
> It has to do with the limits of the finger_joint, in the **robotiq_arg2f_140_model_macro.xacro**
> line 169:
> `<limit lower="0" upper="0.775" velocity="2.0" effort="1000" />`
> increase the upper to close it further.
> 
> My gazebo is Version 7.0.0. (ros kinetic)

Hi, I solved the problem by following the below pull in official repo of Robotiq (https://github.com/ros-industrial/robotiq/pull/157/commits/74f4423b739280007ad1364073d1c680ca79fd40). Thanks for your clue.

Regards!
Rui Cao
