### ISSUE TITLE
Cannot locate rosdep definition for [icl_phri_ur5_robotiq_arg140_description

### ISSUE THREAD

**Issue by iameijaz** [intuitivecomputing/ur5_with_robotiq_gripper#7]
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
icl_ur5_setup_moveit_config: Cannot locate rosdep definition for [icl_phri_ur5_robotiq_arg140_description]

ROS Melodic (Ubuntu 18.04)

**Comment by jhaardt** [comment]
I used Ros Kinetic, since I finished my thesis years ago. I don't exactly
know the ins and outs exactly. But dependencies changed with verying,  Ros
and Package versions. Sorry I can't help you in updating the dependencies.

Verbit ***@***.***> schrieb am Fr., 29. Dez. 2023, 17:51:

**Comment by iameijaz** [comment]
Thanks, I have resolved the issue, it was a missing dependency which I looked up and installed from this repo:  https://github.com/intuitivecomputing/icl_phri_ur5

and then after running rosdep, it was resolved. by the way, how can I contact you?

**Comment by jhaardt** [comment]
Send me a massage through my contact form on my website. www.haardt.design
. I will answer you with my mail address.

Verbit ***@***.***> schrieb am Fr., 29. Dez. 2023, 18:01:
